use crate::gpio::*;
use core::marker::PhantomData;

pub struct StaticMemoryController {
    _d0: PhantomData<Pc0<PfA>>,
    _d1: PhantomData<Pc1<PfA>>,
    _d2: PhantomData<Pc2<PfA>>,
    _d3: PhantomData<Pc3<PfA>>,
    _d4: PhantomData<Pc4<PfA>>,
    _d5: PhantomData<Pc5<PfA>>,
    _d6: PhantomData<Pc6<PfA>>,
    _d7: PhantomData<Pc7<PfA>>,

    _a0: PhantomData<Pc18<PfA>>,
    _a1: PhantomData<Pc19<PfA>>,
    _a2: PhantomData<Pc20<PfA>>,
    _a3: PhantomData<Pc21<PfA>>,
    _a4: PhantomData<Pc22<PfA>>,
    _a5: PhantomData<Pc23<PfA>>,
    _a6: PhantomData<Pc24<PfA>>,
    _a7: PhantomData<Pc25<PfA>>,
    _a8: PhantomData<Pc26<PfA>>,
    _a9: PhantomData<Pc27<PfA>>,
    _a10: PhantomData<Pc28<PfA>>,
    _a11: PhantomData<Pc29<PfA>>,
    _a12: PhantomData<Pc30<PfA>>,
    _a13: PhantomData<Pc31<PfA>>,
    _a14: PhantomData<Pa18<PfC>>,
    _a15: PhantomData<Pa19<PfC>>,
    _a16: PhantomData<Pa20<PfC>>,
    _a17: PhantomData<Pa0<PfC>>,
    _a18: PhantomData<Pa1<PfC>>,
    _a19: PhantomData<Pa23<PfC>>,
    _a20: PhantomData<Pa24<PfC>>,
    _a21: PhantomData<Pc16<PfA>>,
    _a22: PhantomData<Pc17<PfA>>,
    _a23: PhantomData<Pa25<PfC>>,
}

impl StaticMemoryController {
    pub fn new(
        _d0: Pc0<PfA>,
        _d1: Pc1<PfA>,
        _d2: Pc2<PfA>,
        _d3: Pc3<PfA>,
        _d4: Pc4<PfA>,
        _d5: Pc5<PfA>,
        _d6: Pc6<PfA>,
        _d7: Pc7<PfA>,

        _a0: Pc18<PfA>,
        _a1: Pc19<PfA>,
        _a2: Pc20<PfA>,
        _a3: Pc21<PfA>,
        _a4: Pc22<PfA>,
        _a5: Pc23<PfA>,
        _a6: Pc24<PfA>,
        _a7: Pc25<PfA>,
        _a8: Pc26<PfA>,
        _a9: Pc27<PfA>,
        _a10: Pc28<PfA>,
        _a11: Pc29<PfA>,
        _a12: Pc30<PfA>,
        _a13: Pc31<PfA>,
        _a14: Pa18<PfC>,
        _a15: Pa19<PfC>,
        _a16: Pa20<PfC>,
        _a17: Pa0<PfC>,
        _a18: Pa1<PfC>,
        _a19: Pa23<PfC>,
        _a20: Pa24<PfC>,
        _a21: Pc16<PfA>,
        _a22: Pc17<PfA>,
        _a23: Pa25<PfC>,
    ) -> Self {
        StaticMemoryController {
            _d0: PhantomData,
            _d1: PhantomData,
            _d2: PhantomData,
            _d3: PhantomData,
            _d4: PhantomData,
            _d5: PhantomData,
            _d6: PhantomData,
            _d7: PhantomData,

            _a0: PhantomData,
            _a1: PhantomData,
            _a2: PhantomData,
            _a3: PhantomData,
            _a4: PhantomData,
            _a5: PhantomData,
            _a6: PhantomData,
            _a7: PhantomData,
            _a8: PhantomData,
            _a9: PhantomData,
            _a10: PhantomData,
            _a11: PhantomData,
            _a12: PhantomData,
            _a13: PhantomData,
            _a14: PhantomData,
            _a15: PhantomData,
            _a16: PhantomData,
            _a17: PhantomData,
            _a18: PhantomData,
            _a19: PhantomData,
            _a20: PhantomData,
            _a21: PhantomData,
            _a22: PhantomData,
            _a23: PhantomData,    
        }
    }
}
